### ISSUE TITLE
Random nether star in language GUI

### ISSUE THREAD

**Issue by obvTiger** [McPlayHDnet/McPlayHD.net#158]
![grafik](https://user-images.githubusercontent.com/83970850/166018463-86272f4b-6790-439d-b2ff-66167632b04a.png)

**Comment by McPlayHD** [comment]
It shows the row of the currently selected language.
The star on top shows the column.
I know the star to the left does not make a lot of sense right now since there is only one line of languages but I programmed it modular and the idea is that when there are like 10 languages you can still see what language is currently selected.

**Comment by McPlayHD** [comment]
Do you think it would be better if there was a star to the left and right and also on top and on the bottom?

**Comment by obvTiger** [comment]
no if there are more languages comming this is perfect
