### ISSUE TITLE
API no data in fastbuilder/short and infinite response

### ISSUE THREAD

**Issue by obvTiger** [McPlayHDnet/McPlayHD.net#160]
I made a request to API with 
`curl https://mcplayhd.net/api/v1/fastbuilder/short/top -H "Content-Type: application/json" -H "Authorization: Bearer [token]"`

and got the response
`{
  "status" : 200,
  "path" : "/fastbuilder/short/top",
  "timeStamp" : "2022-06-15T10:09:44.942Z",
  "processingTime" : 0,
  "data" : {
    "top" : [ ]
  }
}`
it isn't showing any data for short and infinite
it seems that there is no leaderboard for infinite and short in game is this just not done yet or will theese be removed from api/v1/fastbuilder/modes?

**Comment by McPlayHD** [comment]
As you can see in `https://mcplayhd.net/api/v1/fastbuilder/{mode}/stats`, the `leaderboardSize` for both modes is 0.
```json
{
  "status": 200,
  "path": "/fastbuilder/short/stats",
  "timeStamp": "2022-06-15T12:14:59.027Z",
  "processingTime": 1,
  "data": {
    "sums": {
      "games": 584923111,
      "wins": 10527556,
      "blocks": 4491312411
    },
    "maxConfirmedTime": 4000,
    "leaderboardSize": 0,  <---
    "distribution": {
      "..."
```
In Infinite, no one will ever reach the finish line, so there can't be any leaderboard. In Short, we do not create a leaderboard because it's impossible to determine if a player uses disallowed modifications with so short replays.

So no, this is not a bug and it will also not be removed. It simply has no leaderboard.
