### ISSUE TITLE
crasher

### ISSUE THREAD

**Issue by Monmcgt** [McPlayHDnet/McPlayHD.net#57]
exploit can be use to kick random people out of the server
if you want code dm : MC_MzCGT - [ MCGT ]#5920

**Comment by McPlayHD** [comment]
If you really want to help us just explain how the crasher works here and then we can fix it if we find out how and why the Minecraft server responds as it does.

**Comment by Monmcgt** [comment]
> If you really want to help us just explain how the crasher works here and then we can fix it if we find out how and why the Minecraft server responds as it does.

send a lot of data to the server

in this case : book
example : {extra:[{extra:[{extra:[{text:a}],text:a}],text:a}

**Comment by McPlayHD** [comment]
Only if the server accepts your packets. Since this is a server crasher and we already do everything possible to stop crashers I will now close this issue. Abusing books should not be possible on McPlayHD.net as far as I know. Only if you send an extreme amount of data causing the server to overload but in this case, it's considered a **DoS** attack and will be sued if we find out who the cause is.
