### ISSUE TITLE
GM1 Reset Animation Abuse

### ISSUE THREAD

**Issue by SkifffV2** [McPlayHDnet/McPlayHD.net#76]
By using the GM1 reset animation, you can start your time up 1 block.
Instructions:
1: Create a wall or any structure that the GM1 reset animation will take a few seconds to destory
2: Build up 1 block beside the start
3: Jump in the void and then jump on the 1 block you placed beside you
4: right before the GM1 animation breaks your block, jump. 
5: Once the reset is finished you get your blocks back and you can place 2 block under you before you land.
Thus giving you a +1 block up start to your bridge.

If needed I can record a clip of this glitch (without finishing the bridge of course) and send it over.

**Comment by McPlayHD** [comment]
You make a good point there. But that's not because of the GM1 reset animation. You can actually do that with every reset animation or even if you didn't purchase any at all. The animation won't change the fact that the last block will be reset at the latest. Every animation breaks the block in the same order thus making this (an unpractical) but still possible "bug".

**Comment by McPlayHD** [comment]
This should now be fixed.
